# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 16:37
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yanni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingwheel',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuttingwheel',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topicnumber',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicnumber',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
